language: java
sudo: enabled

services:
  - mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON test.* TO 'travis'@'%';";

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
