version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=palindrome
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306

  app:
    image: app:latest
    ports:
      - 8091:8091
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false
    depends_on:
      - docker-mysql
    container_name: wizardly_easley

    api-users:
      build: .
      depends_on:
        - db
      ports:
        - 9090:9090
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - DATABASE_HOST=db
        - DATABASE_USER=root
        - DATABASE_PASSWORD=root
        - DATABASE_NAME=palindrome
        - DATABASE_PORT=3306
        - SERVER_PORT=9090
      restart: always
      networks:
        - common-network